# config/application.yml
defaults: &defaults
  host: localhost:3000
  title: draw.
  description: A place to inspire your artistic creativity. Draw online and share with your friends. Absolutely free.
  canvas:
    default_width: 400
    default_height: 400
    max_width: 800
    max_height: 600
  min_paint_time: 10 #in seconds
  share:
    facebook: https://www.facebook.com/sharer/sharer.php?u={url}
    twitter: https://twitter.com/share?url={url}&text={title}
    tumblr: https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}&title={title}&caption={desc}
  storage:
    s3:
      storage: :s3
      s3_options:
        port: 80
      s3_protocol: http
      s3_permissions: :public_read
    filesystem:
      storage: filesystem
    styles:
      small: "50x50#"
      medium: "120x120#"
  storage_bucket: bbs-dev


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: draw.angelboy.com
  min_paint_time: 900
  storage_bucket: bbs-prod